// File __EUNIT_TestControl_Coffeepot2_533_Testing.cpp generated by E-UNIT program
// Author: colto
// Date: Mon 2019/11/25 at 06:38:06 PM

#define HUMAN_INTERVENTION_TEST_LEVEL 20
#define ALL_TEST_LEVELS 0xFFFF

void AutomatedTestLevelControl(void)
{
    return;
}