// File __EUNIT_TestControl_Lab2Testing_BF609_Core0.cpp generated by E-UNIT program
// Author: colto
// Date: Tue 2019/11/12 at 04:59:53 PM

#define HUMAN_INTERVENTION_TEST_LEVEL 20
#define ALL_TEST_LEVELS 0xFFFF

void AutomatedTestLevelControl(void)
{
    return;
}